apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../resources

patches:
  - target:
      kind: ConfigMap
      name: argocd-cm
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cm
      data:
        kustomize.buildOptions: --load-restrictor LoadRestrictionsNone
