apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: databases
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/seanturner026/atlas-monorepo.git
        revision: main
        directories:
          - path: db/*
  template:
    metadata:
      name: "db-{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/seanturner026/atlas-monorepo.git
        targetRevision: main
        path: "db/{{path.basename}}/k8s/overlays/production"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
