apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db-sql
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: db-sql
      owner: db-sql
